<?php

/**
 * @file
 * Install hooks for this module.
 */

/**
 * Implements hook_install().
 *
 */
function islandora_data_install() {
  module_load_include('inc', 'islandora', 'includes/solution_packs');
  islandora_install_solution_pack('islandora_data');
}

/**
 * Implements hook_uninstall().
 */
function islandora_data_uninstall() {
  module_load_include('inc', 'islandora', 'includes/solution_packs');
  islandora_install_solution_pack('islandora_data', 'uninstall');
}
