<?php

/**
 * @file
 * Handles the creation and display of tabular data objects.
 */

/**
 * Implements hook_theme().
 */
function islandora_data_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_data' => array(
      'template' => 'theme/islandora-data',
      'pattern' => 'islandora_data__',
      'variables' => array('islandora_object' => NULL),
    ),
  );
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_data_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_data');
  // Tabular data Content Model.
  $data_content_model = $connection->repository->constructObject('islandora:sp_data');
  $data_content_model->owner = 'fedoraAdmin';
  $data_content_model->label = 'Islandora Tabular Data Content Model';
  $data_content_model->models = 'fedora-system:ContentModel-3.0';
  // ISLANDORACM Datastream.
  $datastream = $image_content_model->constructDatastream('ISLANDORACM', 'X');
  $datastream->label = 'Islandora content model';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_data_content_model.xml", FALSE);
  $image_content_model->ingestDatastream($datastream);
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $image_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_data_ds_composite_model.xml", FALSE);
  $image_content_model->ingestDatastream($datastream);
  // Tabular Data Collection.
  $data_collection = $connection->repository->constructObject('islandora:sp_data_collection');
  $data_collection->owner = 'fedoraAdmin';
  $data_collection->label = 'Tabular Data Collection';
  $data_collection->models = 'islandora:collectionCModel';
  $data_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Collection Policy Datastream.
  $datastream = $image_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_data_collection_policy.xml", FALSE);
  $image_collection->ingestDatastream($datastream);
  // TN Datastream.
  $datastream = $image_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/folder.png", FALSE);
  $image_collection->ingestDatastream($datastream);
  return array(
    'islandora_data' => array(
      'title' => 'Islandora tabular data',
      'objects' => array(
        $data_content_model,
        $data_collection,
      ),
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_data_islandora_sp_data_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_data', array('islandora_object' => $object));
  return array('' => $output);
}

/**
 * Implements hook_CMODEL_PID_islandora_object_ingested().
 */
function islandora_data_islandora_sp_data_islandora_object_ingested($object) {
  module_load_include('inc', 'islandora_data', 'includes/derivatives');
  islandora_data_create_all_derivatives($object);
}

/**
 * Implements hook_preprocess_theme().
 */
function islandora_data_preprocess_islandora_data(array &$variables) {
  drupal_add_js('misc/form.js');
  drupal_add_js('misc/collapse.js');
  $islandora_object = $variables['islandora_object'];
  $repository = $islandora_object->repository;
  module_load_include('inc', 'islandora', 'includes/datastream');
  module_load_include('inc', 'islandora', 'includes/utilities');

  if (islandora_datastream_access(FEDORA_VIEW_OBJECTS, $islandora_object['DC'])) {
    try {
      $dc = $islandora_object['DC']->content;
      $dc_object = DublinCore::importFromXMLString($dc);
    }
    catch (Exception $e) {
      drupal_set_message(t('Error retrieving object %s %t', array('%s' => $islandora_object->id, '%t' => $e->getMessage())), 'error', FALSE);
    }
  }
  $variables['islandora_dublin_core'] = isset($dc_object) ? $dc_object : NULL;
  $variables['dc_array'] = isset($dc_object) ? $dc_object->asArray() : array();
  $variables['islandora_object_label'] = $islandora_object->label;
  $variables['theme_hook_suggestions'][] = 'islandora_data__' . str_replace(':', '_', $islandora_object->id);
  $variables['parent_collections'] = islandora_get_parents_from_rels_ext($islandora_object);
  global $base_url;

/*
  // Original.
  if (isset($islandora_object['OBJ']) && islandora_datastream_access(FEDORA_VIEW_OBJECTS, $islandora_object['OBJ'])) {
    $orig_file_url = url("islandora/object/{$islandora_object->id}/datastream/OBJ/view", array('absolute' => TRUE));
    $variables['islandora_orig_url'] = $orig_file_url;
    $params = array(
      'title' => $islandora_object->label,
      'path' => $orig_file_url,
    );
    // $variables['islandora_orig_file'] = theme('islandora_data', $params);
    $variables['islandora_content'] = l("Download file", $orig_file_url, array('html' => TRUE));
  }
*/

  // Thumbnail.
  if (isset($islandora_object['TN']) && islandora_datastream_access(FEDORA_VIEW_OBJECTS, $islandora_object['TN'])) {
    $thumbnail_size_url = url("islandora/object/{$islandora_object->id}/datastream/TN/view");
    $params = array(
      'title' => $islandora_object->label,
      'path' => $thumbnail_size_url,
    );
    $variables['islandora_thumbnail_img'] = theme('image', $params);
  }

  // CSV datastream. During development, just present a link to the CSV_DATA datastream.
  // Goal will be to assign $variables['islandora_content'] the URL of the
  // CSV viewer so it shows up in the item display.
  if (isset($islandora_object['CSV_DATA']) && islandora_datastream_access(FEDORA_VIEW_OBJECTS, $islandora_object['CSV_DATA'])) {
    $csv_data_url = url("islandora/object/{$islandora_object->id}/datastream/CSV_DATA/view", array('absolute' => TRUE));
    $variables['islandora_content'] = l(t("Download CSV version: ") . $islandora_object->label, $csv_data_url, array('html' => TRUE));
  }

}

/**
 * Implements hook_islandora_content_model_forms_form_associations().
 */
function islandora_data_islandora_content_model_forms_form_associations() {
  return array(
    'islandora_data_mods_form' => array(
      'content_model' => 'islandora:sp_data',
      'form_name' => 'Basic tabular data MODS form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function islandora_data_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_data');
  return array(
    'Basic tabular data MODS form' => array(
      'form_file' => "$module_path/xml/islandora_data_form_mods.xml",
    ),
  );
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_data_islandora_sp_data_islandora_ingest_steps() {
  return array(
    'islandora_data' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_data_upload_form',
      'module' => 'islandora_data',
      'file' => 'includes/data_upload.form.inc',
    ),
  );
}
